version: '3.8'

services:
  # FastAPI application service
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount current directory into /app for live code reload
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/simplenotes

  # PostgreSQL database service
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simplenotes
    ports:
      - "5432:5432"  # Keep mapped for easy local access via psql/clients

  # Optional: pgAdmin web UI for PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"  # Access pgAdmin at http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
